repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.97.0
      hooks:
          - id: terraform_fmt

    - repo: https://github.com/aws-cloudformation/cfn-lint
      rev: v0.85.1
      hooks:
          - id: cfn-lint
            files: cloudFormation/.*\.(json|yml|yaml)$

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.1.0"
      hooks:
          - id: prettier
            args: ["--tab-width", "4", "--print-width", "80"]

    - repo: https://github.com/tbroadley/spellchecker-cli
      rev: v6.2.0
      hooks:
          - id: spellchecker-cli
            args: ["-l", "en-GB", "-d", ".spelling", "-f", "README.md"]
            name: spellcheck
            language_version: 18.19.1
            types: [markdown]
            stages:
                - "pre-commit"
