---
AWSTemplateFormatVersion: 2010-09-09
Description: template to create basic ec2 to be used for linux training

Parameters:

  linuxDistro:
    Type: 'AWS::EC2::Image::Id'
    Default: ami-0fb391cce7a602d1f
    AllowedValues:
      - ami-0fb391cce7a602d1f
      - ami-035c5dc086849b5de
    Description: ubuntu ami-ofb391cce7a602d1f or redhat ami-035c5dc086849b5de

  VpcId:
    Type: 'String'
    Description: ID of vpc for the sg
    Default: vpc-xxxxxxxxxxxxxxxxx

  AZ:
    Type: 'String'
    Description: the AV for the ec2 instance
    Default: eu-west-2a 
    AllowedValues:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c

Resources:

  keyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: "linuxServerKeyPair"


  sshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This sg is to allow ssh into the ec2
      GroupName: sshInbound
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  devloperEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref linuxDistro
      InstanceType: "t2.micro"
      AvailabilityZone: !Ref AZ
      SecurityGroupIds: 
        - !Ref sshSecurityGroup
      KeyName: !Ref keyPair
...
